#index:
#    path: /
#    controller: App\Controller\DefaultController::index

productos:
    path: /
    controller: App\Controller\ProductoController::index

landing:
    path: /landing
    controller: App\Controller\AuthController::landingAuth

crearProducto:
    path: /crear-producto
    controller: App\Controller\ProductoController::crearProducto

crearCategoria:
    path: /crear-categoria
    controller: App\Controller\CategoriaController::crearCategoria

mostrarProductos: 
    path: /mostrar-productos
    controller: App\Controller\ProductoController::mostrarProductos

mostrarProducto:
    path: /producto/{id}
    controller: App\Controller\ProductoController::mostrarProducto

datosFacturacion:
    path: /mis-datos
    controller: App\Controller\DatosFacturacionController::gestionDatos

gestionCategorias:
    path: /gestion-categorias
    controller: App\Controller\CategoriaController::gestionCategorias

categoria_editar:
    path: /categoria-editar/{id}
    controller: App\Controller\CategoriaController::update

categoria_eliminar:
    path: /categoria-eliminar/{id}
    controller: App\Controller\CategoriaController::delete

gestionProductos:
    path: /gestion-productos
    controller: App\Controller\ProductoController::gestionProductos

producto_editar:
    path: /producto-editar/{id}
    controller: App\Controller\ProductoController::update

producto_eliminar:
    path: /producto-eliminar/{id}
    controller: App\Controller\ProductoController::delete

#carrito
carrito_index:
    path: /carrito
    controller: App\Controller\CarritoController::index

carrito_add:
    path: /carrito-add/{id}
    controller: App\Controller\CarritoController::addItem
    methods: GET|HEAD #[GET,POST]  

carrito_remove:
    path: /carrito-remove/{index}
    controller: App\Controller\CarritoController::removeItem
    methods: GET|HEAD

ajax_request:
    path: /ajax_request
    controller: App\Controller\CarritoController::guardar_quantity_session

carrito_up:
    path: /carrito-up/{index}
    controller: App\Controller\CarritoController::upItem
    methods: GET|HEAD

carrito_down:
    path: /carrito-down/{index}
    controller: App\Controller\CarritoController::downItem
    methods: GET|HEAD

carrito_delete:
    path: /carrito-delete
    controller: App\Controller\CarritoController::delete_all

#checkout
checkout_sesion:
    path: /checkout-sesion
    controller: App\Controller\CarritoController::checkout_session

#ProdByCat
prod_categoria:
    path: /categoria/{categoria}
    controller: App\Controller\ProductoController::mostrarProdByCat



