#index:
#    path: /
#    controller: App\Controller\DefaultController::index

productos:
    path: /productos
    controller: App\Controller\ProductoController::index

landing:
    path: /landing
    controller: App\Controller\AuthController::landingAuth

crearProducto:
    path: /crear-producto
    controller: App\Controller\ProductoController::crearProducto

crearCategoria:
    path: /crear-categoria
    controller: App\Controller\CategoriaController::crearCategoria

mostrarProductos: 
    path: /mostrar-productos
    controller: App\Controller\ProductoController::mostrarProductos

mostrarProducto:
    path: /producto/{id}
    controller: App\Controller\ProductoController::mostrarProducto

datosFacturacion:
    path: /mis-datos
    controller: App\Controller\DatosFacturacionController::gestionDatos

gestionCategorias:
    path: /gestion-categorias
    controller: App\Controller\CategoriaController::gestionCategorias

categoria_editar:
    path: /categoria-editar/{id}
    controller: App\Controller\CategoriaController::update

categoria_eliminar:
    path: /categoria-eliminar/{id}
    controller: App\Controller\CategoriaController::delete




