#index:
#    path: /
#    controller: App\Controller\DefaultController::index

productos:
    path: /productos
    controller: App\Controller\ProductoController::index

landing:
    path: /landing
    controller: App\Controller\AuthController::landingAuth

crearProducto:
    path: /crear-producto
    controller: App\Controller\ProductoController::crearProducto

crearCategoria:
    path: /crear-categoria
    controller: App\Controller\CategoriaController::crearCategoria

mostrarProductos: 
    path: /mostrar-productos
    controller: App\Controller\ProductoController::mostrarProductos

mostrarProducto:
    path: /producto/{id}
    controller: App\Controller\ProductoController::mostrarProducto

